EmreAydogduoglu.UI/Controllers/ArticleController.cs
using EmreAydogduoglu.Business.Abstract;
using EmreAydogduoglu.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.Controllers
{
    public class ArticleController : Controller
    {
        private IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        public IActionResult Index(int? id)
        {
            if (id == null || id == 0)
            {
                ArticleListViewModel model = new ArticleListViewModel
                {
                    Articles = _articleService.GetArticlesByDate()
                };
                return View(model);
            }
            else
            {
                ArticleListViewModel model = new ArticleListViewModel
                {
                    Articles = _articleService.GetArticlesByCategoryId((int)id)
                };
                return View(model);
            }
        }

        public IActionResult Detail(int id)
        {
            var model = new ArticleByIdViewModel
            {
                Article = _articleService.GetArticleById(id)
            };
            return View(model);
        }
    }
}

EmreAydogduoglu.UI/ViewComponents/CategoryListViewComponent.cs
using EmreAydogduoglu.Business.Abstract;
using EmreAydogduoglu.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            CategoryListViewModel model = new CategoryListViewModel
            {
                Categories = _categoryService.GetCategories()
            };
            return View(model);
        }
    }
}

EmreAydogduoglu.UI/Views/Shared/_ArticleLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/article_layout.css" rel="stylesheet" />
</head>
<body class="">

    <nav class="navbar navbar-expand-lg navbar-light bg-danger">
        <div class="container-fluid">
            <a class="navbar-brand text-white" asp-controller="Article" asp-action="Index">Menü</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-white active" aria-current="page" asp-controller="Article" asp-action="Index">Anasayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Kişisel Bilgiler</a>
                    </li>
                    @await Component.InvokeAsync("CategoryList")
                </ul>
            </div>
        </div>
    </nav>

    <main class="mx-5">
        @RenderBody()
    </main>

    <footer class="bg-light text-center text-lg-start">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © @DateTime.Now.Year Emre Aydoğduoğlu tarafından Asp.NetCore 6 ile oluşturulmuştur.
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>

EmreAydogduoglu.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmreAydogduoglu</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
    <div class="container mt-5">
        <main role="main" class="pb-1">
            @RenderBody()
        </main>
    </div>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>