EmreAydogduoglu.UI/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EmreAydogduoglu.UI/Controllers/ArticleController.cs
using EmreAydogduoglu.Business.Abstract;
using EmreAydogduoglu.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.Controllers
{
    public class ArticleController : Controller
    {
        private IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        public IActionResult Index(int? id)
        {
            if (id == null || id == 0)
            {
                ArticleListViewModel model = new ArticleListViewModel
                {
                    Articles = _articleService.GetArticlesByDate()
                };
                return View(model);
            }
            else
            {
                ArticleListViewModel model = new ArticleListViewModel
                {
                    Articles = _articleService.GetArticlesByCategoryId((int)id)
                };
                return View(model);
            }
        }

        public IActionResult Detail(int id)
        {
            var model = new ArticleByIdViewModel
            {
                Article = _articleService.GetArticleById(id)
            };
            return View(model);
        }
    }
}

EmreAydogduoglu.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NotFound(int code)
        {
            ViewBag.Code = code;
            return View();
        }
    }
}

EmreAydogduoglu.UI/ViewComponents/CvDownloadViewComponent.cs
using EmreAydogduoglu.Business.Abstract;
using EmreAydogduoglu.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.ViewComponents
{
    public class CvDownloadViewComponent : ViewComponent
    {
        private IPersonService _personService;

        public CvDownloadViewComponent(IPersonService personService)
        {
            _personService = personService;
        }

        public IViewComponentResult Invoke()
        {
            PersonViewModel model = new PersonViewModel
            {
                Person = _personService.GetPerson(1)
            };
            return View(model);
        }
    }
}

EmreAydogduoglu.UI/ViewComponents/PersonViewComponent.cs
using EmreAydogduoglu.Business.Abstract;
using EmreAydogduoglu.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.ViewComponents
{
    public class PersonViewComponent : ViewComponent
    {
        private readonly IPersonService _personService;

        public PersonViewComponent(IPersonService personService)
        {
            _personService = personService;
        }

        public IViewComponentResult Invoke()
        {
            PersonViewModel model = new PersonViewModel
            {
                Person = _personService.GetPerson(1)
            };
            return View(model);
        }
    }
}

EmreAydogduoglu.UI/ViewComponents/SkillListViewComponent.cs
using EmreAydogduoglu.Data.Abstract;
using EmreAydogduoglu.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmreAydogduoglu.UI.ViewComponents
{
    public class SkillListViewComponent : ViewComponent
    {
        private ISkillDal _skillDal;

        public SkillListViewComponent(ISkillDal skillDal)
        {
            _skillDal = skillDal;
        }

        public IViewComponentResult Invoke()
        {
            SkillListViewModel model = new SkillListViewModel
            {
                Skills = _skillDal.GetAll()
            };
            return View(model);
        }
    }
}

EmreAydogduoglu.UI/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="tr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Emre,Aydoğduoğlu,Kişisel,Web,Site" />
        <meta name="author" content="Emre Aydoğduoğlu" />
        <title>Emre Aydoğduoğlu - Kişisel Web Sitesi</title>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="~/css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            @await Component.InvokeAsync("PersonImage")
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Hakkında</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Eğitim</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Beceriler</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#projects">Projeler</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#socials">İletişim</a></li>
                    <br />
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Article" asp-action="Index">Blog</a></li>
                    <br />
                    @await Component.InvokeAsync("CvDownload")
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- About-->
            @await Component.InvokeAsync("Person")
            <hr class="m-0" />
            <!-- Education-->
            @await Component.InvokeAsync("EducationList")
            <hr class="m-0" />
            <!-- Skills-->
            @await Component.InvokeAsync("SkillList")
            <hr class="m-0" />
            <!-- Projects-->
            @await Component.InvokeAsync("ProjectList")
            <hr class="m-0" />
            <!-- Social-->
            @await Component.InvokeAsync("SocialList")
            
        </div>
        <!-- Bootstrap core JS-->
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="~/js/scripts.js"></script>
    </body>
</html>

EmreAydogduoglu.UI/Views/Home/NotFound.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="d-flex align-items-center justify-content-center vh-100">
    <div class="text-center row">
        <div class=" col-md-6">
            <img src="~/assets/img/notfound.png" alt="Not Found"
                 class="img-fluid">
        </div>
        <div class=" col-md-6 mt-5">
            <p class="fs-3"> <span class="text-danger">Opps!</span> Sayfa bulunamadı.</p>
            <p class="lead">
                Hata Kodu : @ViewBag.Code
            </p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Anasayfa'ya Git</a>
        </div>

    </div>
</div>